// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW0YltuGO7QdmVZGNX0H4wYCom5dSIBQE',
    appId: '1:609978247834:web:ea1d302a5ce0b770840d23',
    messagingSenderId: '609978247834',
    projectId: 'ncb-firebase-a9050',
    authDomain: 'ncb-firebase-a9050.firebaseapp.com',
    databaseURL: 'https://ncb-firebase-a9050-default-rtdb.firebaseio.com',
    storageBucket: 'ncb-firebase-a9050.appspot.com',
    measurementId: 'G-HDKJ9T1PFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARXuOGJ8AzSobIeBk1C8JCnzh323CJQm8',
    appId: '1:609978247834:android:62eb29561f382c60840d23',
    messagingSenderId: '609978247834',
    projectId: 'ncb-firebase-a9050',
    databaseURL: 'https://ncb-firebase-a9050-default-rtdb.firebaseio.com',
    storageBucket: 'ncb-firebase-a9050.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAadV4laLU4aa-UE_f_VjXiIbq6V_2u0zM',
    appId: '1:609978247834:ios:839a38ae7063a5c4840d23',
    messagingSenderId: '609978247834',
    projectId: 'ncb-firebase-a9050',
    databaseURL: 'https://ncb-firebase-a9050-default-rtdb.firebaseio.com',
    storageBucket: 'ncb-firebase-a9050.appspot.com',
    iosBundleId: 'in.wi.ncb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAadV4laLU4aa-UE_f_VjXiIbq6V_2u0zM',
    appId: '1:609978247834:ios:839a38ae7063a5c4840d23',
    messagingSenderId: '609978247834',
    projectId: 'ncb-firebase-a9050',
    databaseURL: 'https://ncb-firebase-a9050-default-rtdb.firebaseio.com',
    storageBucket: 'ncb-firebase-a9050.appspot.com',
    iosBundleId: 'in.wi.ncb',
  );
}
