// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP6abDqUd7N4GRlnliym4Kmj4SWsrYGos',
    appId: '1:136540643262:web:974f3e1816519fd833e3ef',
    messagingSenderId: '136540643262',
    projectId: 'new-community-bible',
    authDomain: 'new-community-bible.firebaseapp.com',
    storageBucket: 'new-community-bible.appspot.com',
    measurementId: 'G-W98M0WC516',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLIBJA3kCvO4-IPJoT0m_QKYHlTbVwzNc',
    appId: '1:136540643262:android:73d1749350c0bf6833e3ef',
    messagingSenderId: '136540643262',
    projectId: 'new-community-bible',
    storageBucket: 'new-community-bible.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALDUi9H2yPxoW8LKOPvyw435NIBEKyEfY',
    appId: '1:136540643262:ios:654f921aac49e21833e3ef',
    messagingSenderId: '136540643262',
    projectId: 'new-community-bible',
    storageBucket: 'new-community-bible.appspot.com',
    iosClientId: '136540643262-seh6hl1iuc8tb3i5sa2r7s887a8n6igd.apps.googleusercontent.com',
    iosBundleId: 'in.wi.ncb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALDUi9H2yPxoW8LKOPvyw435NIBEKyEfY',
    appId: '1:136540643262:ios:654f921aac49e21833e3ef',
    messagingSenderId: '136540643262',
    projectId: 'new-community-bible',
    storageBucket: 'new-community-bible.appspot.com',
    iosClientId: '136540643262-seh6hl1iuc8tb3i5sa2r7s887a8n6igd.apps.googleusercontent.com',
    iosBundleId: 'in.wi.ncb',
  );
}
